# packageExtensions:
#   "@nestjs/core@*":
#     peerDependenciesMeta:
#       "@nestjs/platform-express":
#         optional: true
#   "@nestjs/graphql@*":
#     dependencies:
#       apollo-env: 0.6.5
#       graphql-tools: 6.0.13
#     peerDependencies:
#       apollo-server-express: "*"
      
nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.1.0.cjs
